---

hub: "flusight" # must be one of 'flusight', 'flu metrocast', 'rsv', 'covid19'

evaluation_start_date: "2026-01-01" # YYYY-MM-DD
evaluation_end_date: "2026-03-01" # dates are inclusive on both ends [,]

target: "wk inc flu hosp" # only scores on target at a time

models: {
    "UGA-flucast-Copycat": "/Users/emprzy/Desktop/epibench-test/UGA-flucast-Copycat", 
    "UNC_IDD-InfluPaint": "/Users/emprzy/Desktop/epibench-test/UNC-IDD-InfluPaint", 
    "UVAFluX-CESGCN": "/Users/emprzy/Desktop/epibench-test/UVAFluX-CESGCN"
} # only scores quantile data right now
output_path: "/Users/emprzy/Desktop/"