---

hub: flusight" # must be one of 'flusight', 'flu metrocast', 'rsv', 'covid19'

dates:
  start_date: "2026-01-01", 
  end_date: "2026-01-30",
  freq: "1 week" # format must be: "<num> week" or "<num> weeks"
# or it could be a list of dates: [YYYY-MM-DD, YYYY-MM-DD, ...]. no need to specify frequency in this format 
# e.g.,
# dates: 
#   - "YYYY-MM-DD"
#   - "YYYY-MM-DD"
#   - "YYYY-MM-DD"

vintaging: true

output_path: "output"