---

hub_path: "https://github.com/CDCgov/covid19-forecast-hub" 

challenge_name: "my-covid-challenge_winter"

targets: ["wk inc covid hosp", "wk inc covid prop ed visits"] 

dates: {
    start_date: 2025-01-09, 
    end_date: 2026-02-28,
    freq: "2 weeks" 
} 

vintaging: TRUE
vintaging_method: "as_of" 

output_path: "output"